wget https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.doc
wget https://file-examples.com/wp-content/uploads/2017/02/file-sample_500kB.doc
wget https://file-examples.com/wp-content/uploads/2017/02/file-sample_1MB.doc
wget https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx
wget https://file-examples.com/wp-content/uploads/2017/02/file-sample_500kB.docx
wget https://file-examples.com/wp-content/uploads/2017/02/file-sample_1MB.docx
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_10.xls
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_50.xls
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_100.xls
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_1000.xls
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLS_5000.xls
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_10.xlsx
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_50.xlsx
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_100.xlsx
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_1000.xlsx
wget https://file-examples.com/wp-content/uploads/2017/02/file_example_XLSX_5000.xlsx
wget https://file-examples.com/wp-content/uploads/2017/08/file_example_PPT_250kB.ppt
wget https://file-examples.com/wp-content/uploads/2017/08/file_example_PPT_500kB.ppt
wget https://file-examples.com/wp-content/uploads/2017/08/file_example_PPT_1MB.ppt
wget https://file-examples.com/wp-content/uploads/2017/10/file-sample_150kB.pdf
wget https://file-examples.com/wp-content/uploads/2017/10/file-example_PDF_500_kB.pdf
wget https://file-examples.com/wp-content/uploads/2017/10/file-example_PDF_1MB.pdf
wget https://file-examples.com/wp-content/uploads/2017/10/file-sample_100kB.odt
wget https://file-examples.com/wp-content/uploads/2017/10/file-sample_500kB.odt
wget https://file-examples.com/wp-content/uploads/2017/10/file-sample_1MB.odt
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODS_10.ods
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODS_100.ods
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODS_1000.ods
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODS_5000.ods
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODP_200kB.odp
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODP_500kB.odp
wget https://file-examples.com/wp-content/uploads/2017/10/file_example_ODP_1MB.odp
wget https://sample-videos.com/csv/Sample-Spreadsheet-100-rows.csv
wget https://sample-videos.com/csv/Sample-Spreadsheet-1000-rows.csv
wget https://sample-videos.com/csv/Sample-Spreadsheet-5000-rows.csv
wget https://sample-videos.com/csv/Sample-Spreadsheet-10000-rows.csv
wget https://sample-videos.com/csv/Sample-Spreadsheet-50000-rows.csv
wget https://sample-videos.com/csv/Sample-Spreadsheet-100000-rows.csv
wget https://sample-videos.com/csv/Sample-Spreadsheet-500000-rows.csv